version: '3.8'

services:
   database:
      image: mysql:5
      container_name: database
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
         - ./docker-database-volume:/var/lib/mysql

   phpmyadmin:
      depends_on:
       - database
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: database